### ISSUE TITLE
How to use my own datasets

### ISSUE THREAD

**Issue by wangtingyu-gjw** [LinghaoChan/HumanMAC#11] opened 2023-12-20 04:16 UTC
Hello, if I want to experiment on your method with my own datasets, how should I modify the dataset processing file. I see that you used the CMU-Mocap and AMASS datasets to evaluate the method. Can you share the processing files of these two datasets to make better use of the method? Or can you show me how to modify the dataset file to fit my own datasets and experiment with your method? Thank you very much!

**Comment by LinghaoChan** [comment] 2023-12-20 05:46
@wangtingyu-gjw Thanks for your interest. 

The CMU-Mocap is a subset of the AMASS dataset. Therefore, I will tell you how to use AMASS. 

You can download the AMASS dataset from the [website](https://amass.is.tue.mpg.de/download.php) (SMPL+H G). For the SMPL-H format, you can use SMPL-H or only use the body-only format (SMPL format, we use). If you would like to use the body-only format, please refer to [this](https://github.com/LinghaoChan/UniMoCap/blob/6fcdbe9498ffa6f82fefeb5099be865e5d09daea/raw_pose_processing.py#L95). If you are not familiar with how to process SMPL-H to SMPL or the usage of AMASS, please try [UniMocap](https://github.com/LinghaoChan/UniMoCap). 

For your data, I'm not sure about your data format. The dataloader of the training supports the sequences of skeleton sequences of motion.

**Comment by wangtingyu-gjw** [comment] 2023-12-20 06:24
Ok, thanks again!

**Comment by LinghaoChan** [comment] 2023-12-20 07:20
Seems the issue is resolved. I close it now. Any further questions, plz reopen it or raise another issue.

**Closed as completed by LinghaoChan** 2023-12-20 07:20 UTC
Labels: question
